// GENERATED by scripts/gen-design-tokens.sh from
// assets/templates/design-tokens/tokens.toml — DO NOT EDIT.
// Add or change a token at the source and re-run the generator.

import 'package:flutter/widgets.dart';

/// Semantic design tokens. Never reference a raw Color or EdgeInsets at a
/// call site — read a role from here so light and dark stay in step.
@immutable
class AppTokens {
  const AppTokens({
    required this.canvas,
    required this.surface,
    required this.raised,
    required this.chrome,
    required this.zebra,
    required this.text,
    required this.muted,
    required this.subtle,
    required this.accent,
    required this.accentVivid,
    required this.accentHover,
    required this.accentTint,
    required this.cool,
    required this.coolSurface,
    required this.focus,
    required this.statusMet,
    required this.statusMetSurface,
    required this.statusGap,
    required this.statusGapSurface,
    required this.statusVoid,
    required this.statusVoidSurface,
    required this.destructive,
  });

  final Color canvas;
  final Color surface;
  final Color raised;
  final Color chrome;
  final Color zebra;
  final Color text;
  final Color muted;
  final Color subtle;
  final Color accent;
  final Color accentVivid;
  final Color accentHover;
  final Color accentTint;
  final Color cool;
  final Color coolSurface;
  final Color focus;
  final Color statusMet;
  final Color statusMetSurface;
  final Color statusGap;
  final Color statusGapSurface;
  final Color statusVoid;
  final Color statusVoidSurface;
  final Color destructive;

  static const AppTokens light = AppTokens(
    canvas: Color(0xFFFFFFFF),
    surface: Color(0xFFF7F6F4),
    raised: Color(0xFFF1EFEC),
    chrome: Color(0xFFE7E4E0),
    zebra: Color(0xFFFAF9F7),
    text: Color(0xFF231F20),
    muted: Color(0xFF55565A),
    subtle: Color(0xFF6E6F71),
    accent: Color(0xFFA85417),
    accentVivid: Color(0xFFDF7C35),
    accentHover: Color(0xFFC4661F),
    accentTint: Color(0xFFFBEFE6),
    cool: Color(0xFF1F4E79),
    coolSurface: Color(0xFFEDF3F7),
    focus: Color(0xFFA85417),
    statusMet: Color(0xFF1E6F4E),
    statusMetSurface: Color(0xFFE7F3EC),
    statusGap: Color(0xFFA85417),
    statusGapSurface: Color(0xFFFBEFE6),
    statusVoid: Color(0xFF5B5F66),
    statusVoidSurface: Color(0xFFEFEFF1),
    destructive: Color(0xFFA8331B),
  );

  static const AppTokens dark = AppTokens(
    canvas: Color(0xFF14181C),
    surface: Color(0xFF1C2126),
    raised: Color(0xFF252B31),
    chrome: Color(0xFF2E353C),
    zebra: Color(0xFF191E23),
    text: Color(0xFFEDF0F2),
    muted: Color(0xFFB4BFC7),
    subtle: Color(0xFF93A0A9),
    accent: Color(0xFFF0955A),
    accentVivid: Color(0xFFF0955A),
    accentHover: Color(0xFFF7AC7B),
    accentTint: Color(0xFF2E2119),
    cool: Color(0xFF8FB9D0),
    coolSurface: Color(0xFF182430),
    focus: Color(0xFFF0955A),
    statusMet: Color(0xFF6FD1A0),
    statusMetSurface: Color(0xFF152620),
    statusGap: Color(0xFFF0955A),
    statusGapSurface: Color(0xFF2E2119),
    statusVoid: Color(0xFFA9B3BB),
    statusVoidSurface: Color(0xFF232830),
    destructive: Color(0xFFE0705A),
  );
}

/// Spacing scale on a 4pt base.
abstract final class AppSpace {
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 24;
  static const double s6 = 32;
  static const double s7 = 48;
  static const double s8 = 72;
}

/// Corner radii. Flat 2.0: no borders, no layout shadows.
abstract final class AppShape {
  static const double radius = 5;
  static const double radiusLg = 8;
}

/// Asymmetric motion — exit is faster because the user already chose it.
abstract final class AppMotion {
  static const Duration enter = Duration(milliseconds: 200);
  static const Duration exit = Duration(milliseconds: 140);
}

/// Layout constants shared with the web shell.
abstract final class AppLayout {
  /// Material 3 compact→medium. Below this, destinations live in a bottom bar.
  static const double breakpointSm = 600;
  static const double navRail = 64;
  static const double topbar = 56;
  static const double tabbar = 64;
}
