#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# Generate the web and Flutter theme files from the single token source.
#
#   bash scripts/gen-design-tokens.sh <repo-root>
#
# Reads  assets/templates/design-tokens/tokens.toml
# Writes web/src/theme.css
#        mobile/lib/core/theme/tokens.dart
#
# Both outputs are overwritten wholesale and carry a DO-NOT-EDIT banner. If you
# need a new token, add it to tokens.toml and re-run — editing an output is a
# change that the next run silently reverts.
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

ROOT="${1:-.}"
SRC="$ROOT/assets/templates/design-tokens/tokens.toml"
[ -f "$SRC" ] || { echo "error: token source not found at $SRC" >&2; exit 1; }

command -v python3 >/dev/null || { echo "error: python3 required" >&2; exit 1; }

python3 - "$ROOT" "$SRC" <<'ENDPY'
import os, sys, re

root, src = sys.argv[1], sys.argv[2]

# Minimal TOML reader: this file is machine-written and shape-stable, so a
# dependency-free parser keeps the generator runnable on a clean checkout.
def parse(path):
    """Minimal TOML reader.

    Comment stripping must not touch a '#' inside a quoted string, or every
    hex colour silently becomes empty and the generated Dart emits
    `Color(0xFF)` — which does not compile, but only fails at build time far
    from the cause. Strip only an unquoted '#'.
    """
    data, section = {}, None
    for raw in open(path):
        line, quoted = [], False
        for ch in raw:
            if ch == '"':
                quoted = not quoted
            if ch == '#' and not quoted:
                break
            line.append(ch)
        line = ''.join(line).strip()
        if not line:
            continue
        m = re.match(r'^\[([\w.]+)\]$', line)
        if m:
            section = m.group(1); data.setdefault(section, {}); continue
        m = re.match(r'^(\w+)\s*=\s*(.+)$', line)
        if m and section:
            v = m.group(2).strip()
            if v.startswith('"') and v.endswith('"'):
                v = v[1:-1]
            data[section][m.group(1)] = v
    return data

t = parse(src)
light, dark = t.get('color.light', {}), t.get('color.dark', {})
space, typ  = t.get('space', {}), t.get('type', {})
shape, mot  = t.get('shape', {}), t.get('motion', {})
layout      = t.get('layout', {})
meta        = t.get('meta', {})

BANNER = ("GENERATED by scripts/gen-design-tokens.sh from\n"
          "assets/templates/design-tokens/tokens.toml — DO NOT EDIT.\n"
          "Add or change a token at the source and re-run the generator.")

def kebab(s):
    return re.sub(r'(?<!^)(?=[A-Z])', '-', s).lower()

# ── web: Tailwind 4 @theme, dark as the base with a light override ─────────
css = [f"/* {BANNER} */", "", "@theme {"]
for k, v in light.items():
    css.append(f"  --color-{kebab(k)}: {v};")
css.append("")
for k, v in space.items():
    css.append(f"  --spacing-{k}: {v};")
css.append("")
css.append(f"  --font-display: {typ.get('display','')};")
css.append(f"  --font-body: {typ.get('body','')};")
css.append(f"  --font-mono: {typ.get('mono','')};")
for k, v in typ.items():
    if k.startswith('size'):
        css.append(f"  --text-{kebab(k[4:])}: {v};")
css.append("")
css.append(f"  --radius: {shape.get('radius','')};")
css.append(f"  --radius-lg: {shape.get('radiusLg','')};")
css.append(f"  --ease-out-brand: {mot.get('ease','')};")
css.append(f"  --duration-enter: {mot.get('durEnter','')};")
css.append(f"  --duration-exit: {mot.get('durExit','')};")
css.append("")
css.append("  /* Material 3 compact→medium, deliberately not Tailwind's 640px */")
css.append(f"  --breakpoint-sm: {layout.get('breakpointSm','600px')};")
for k in ('rail','gutter','navRail','contextPanel','topbar','tabbar'):
    if k in layout:
        css.append(f"  --size-{kebab(k)}: {layout[k]};")
css.append("}")
css.append("")
css.append("/* Dark is applied by class so the choice is explicit, never inferred. */")
css.append("html.dark {")
for k, v in dark.items():
    css.append(f"  --color-{kebab(k)}: {v};")
css.append("}")
css.append("")

web = os.path.join(root, 'web', 'src')
os.makedirs(web, exist_ok=True)
open(os.path.join(web, 'theme.css'), 'w').write("\n".join(css))

# ── Flutter: a typed token class, one per theme ────────────────────────────
def dart_color(hexv):
    return f"Color(0xFF{hexv.lstrip('#').upper()})"

def px(v):
    return re.sub(r'px$', '', v)

d = ["// " + BANNER.replace("\n", "\n// "), "",
     "import 'package:flutter/widgets.dart';", "",
     "/// Semantic design tokens. Never reference a raw Color or EdgeInsets at a",
     "/// call site — read a role from here so light and dark stay in step.",
     "@immutable", "class AppTokens {", "  const AppTokens({"]
for k in light:
    d.append(f"    required this.{k},")
d += ["  });", ""]
for k in light:
    d.append(f"  final Color {k};")
d += ["", "  static const AppTokens light = AppTokens("]
for k, v in light.items():
    d.append(f"    {k}: {dart_color(v)},")
d += ["  );", "", "  static const AppTokens dark = AppTokens("]
for k, v in dark.items():
    d.append(f"    {k}: {dart_color(v)},")
d += ["  );", "}", "",
      "/// Spacing scale on a 4pt base.", "abstract final class AppSpace {"]
for k, v in space.items():
    d.append(f"  static const double {k} = {px(v)};")
d += ["}", "",
      "/// Corner radii. Flat 2.0: no borders, no layout shadows.",
      "abstract final class AppShape {",
      f"  static const double radius = {px(shape.get('radius','5px'))};",
      f"  static const double radiusLg = {px(shape.get('radiusLg','8px'))};",
      "}", "",
      "/// Asymmetric motion — exit is faster because the user already chose it.",
      "abstract final class AppMotion {",
      f"  static const Duration enter = Duration(milliseconds: {re.sub(r'ms$','',mot.get('durEnter','200ms'))});",
      f"  static const Duration exit = Duration(milliseconds: {re.sub(r'ms$','',mot.get('durExit','140ms'))});",
      "}", "",
      "/// Layout constants shared with the web shell.",
      "abstract final class AppLayout {",
      f"  /// Material 3 compact→medium. Below this, destinations live in a bottom bar.",
      f"  static const double breakpointSm = {px(layout.get('breakpointSm','600px'))};",
      f"  static const double navRail = {px(layout.get('navRail','64px'))};",
      f"  static const double topbar = {px(layout.get('topbar','56px'))};",
      f"  static const double tabbar = {px(layout.get('tabbar','64px'))};",
      "}", ""]

mob = os.path.join(root, 'mobile', 'lib', 'core', 'theme')
os.makedirs(mob, exist_ok=True)
open(os.path.join(mob, 'tokens.dart'), 'w').write("\n".join(d))

print(f"  web/src/theme.css                 {len(light)+len(dark)} colors, {len(space)} spacing")
print(f"  mobile/lib/core/theme/tokens.dart {len(light)} roles x 2 themes")
ENDPY

echo "design tokens generated from tokens.toml"
